name: Deploy Bank Card Stock Management

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: bank_card_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Generate Prisma client
      working-directory: ./backend
      run: npm run generate
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/bank_card_test

    - name: Run Prisma migrations
      working-directory: ./backend
      run: npm run migrate:prod
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/bank_card_test

    - name: Seed database
      working-directory: ./backend
      run: npm run seed
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/bank_card_test
        JWT_SECRET: test-secret-key

    - name: Run backend tests
      working-directory: ./backend
      run: npm test
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/bank_card_test
        JWT_SECRET: test-secret-key
        NODE_ENV: test

    - name: Build backend
      working-directory: ./backend
      run: npm run build

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
      env:
        VITE_API_URL: http://localhost:5000/api

    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test
      env:
        CI: true

    # Optional: Deploy to staging/production
    # - name: Deploy to production
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     echo "Deploy to production server"
    #     # Add your deployment commands here
